#!/bin/sh

D=$(dirname "$(readlink -f "$0")")

if [ ! -x "$D"/zforth ]; then
  (
    cd "$D"
    make
    make clean
  )
fi

locwords=$D/forth/local.zf
test -r $locwords || locwords=
$D/zforth $D/forth/core.zf $D/forth/dict.zf $locwords "$@"
